'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Actividades
    Public Property IdTarea As Integer
    Public Property Tema As String
    Public Property Descripcion As String
    Public Property FechaCreacion As Nullable(Of Date)
    Public Property FechaEntrega As Nullable(Of Date)
    Public Property IdMateria As String
    Public Property IdFileStream As Nullable(Of Integer)
    Public Property TiempoRevision As Nullable(Of Date)
    Public Property IdTipoActividad As Nullable(Of Byte)

End Class
