'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Alumnos
    Public Property IdAlumno As Integer
    Public Property Nombre As String
    Public Property Paterno As String
    Public Property Materno As String
    Public Property IdAula As Integer

End Class
