'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Calificaciones
    Public Property IdCalificacion As Long
    Public Property IdActividad As Nullable(Of Integer)
    Public Property IdAlumno As Nullable(Of Integer)
    Public Property Calificacion As Nullable(Of Decimal)

End Class
