'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FileStream
    Public Property Id As Integer
    Public Property StreamId As System.Guid
    Public Property Descripcion As String
    Public Property Extencion As String
    Public Property FileData As Byte()

End Class
