'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Usuario
    Public Property Id As Integer
    Public Property Nombre As String
    Public Property Paterno As String
    Public Property Materno As String
    Public Property Escuela As String
    Public Property Direccion As String
    Public Property Telefono As String
    Public Property Logo As Nullable(Of Integer)

End Class
